[tool.poetry]
name = "cookiecutter"
version = "2.0.0"

description = """\
  A command-line utility that creates projects from project \
  templates, e.g. creating a Python package project from a \
  Python package project template.\
  """

authors = [
    "Audrey Roy Greenfeld <audrey@feldroy.com>"
]

maintainers = [
    "Audrey Roy Greenfeld <audrey@feldroy.com>",
    "Daniel Roy Greenfeld <pydanny@gmail.com>",
    "Hosam Almoghraby <hosam.moghraby@gmail.com>",
]

license = "BSD"
readme = "README.md"

packages = [
    { include = "cookiecutter" }
]

homepage = "https://github.com/cookiecutter/cookiecutter"
documentation = "https://cookiecutter.readthedocs.io"

keywords = [
    "cookiecutter",
    "Python",
    "projects",
    "project templates",
    "Jinja2",
    "skeleton",
    "scaffolding",
    "project directory",
    "package",
    "packaging"
    ]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development",
]


[tool.poetry.build]
generate-setup-file = false


[tool.poetry.dependencies]
python = "^3.6"

binaryornot = "^0.4"
Jinja2 = "^3.0.0"
click = "^7.0"
pyyaml = "^5.3"
jinja2-time = "^0.2"
python-slugify = "^4.0"
requests = "^2.23"


[tool.poetry.dev-dependencies]
tox = "^3.24"
pytest = "^6.2"
pytest-cov = "^3.0"
pytest-mock = "^3.6"
freezegun = "^1.1"
pre-commit = "^1.20"
safety = "^1.10"


[tool.poetry.scripts]
cookiecutter = "cookiecutter.__main__:main"


[tool.black]
skip-string-normalization = true
exclude = '/(tests/hooks-abort-render/hooks|docs\/HelloCookieCutter1)/'
line-length = 88
target-version = ['py39']


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
